# Generated by Django 3.2.25 on 2024-05-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210325_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('feedback', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='phoneno',
            field=models.CharField(default='6304572667', max_length=10),
        ),
    ]
