# Generated by Django 3.2.25 on 2024-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('product', models.CharField(blank=True, default='', max_length=50)),
                ('cdate', models.CharField(max_length=20)),
            ],
        ),
    ]
